sudo: required
language: java
jdk:
  - openjdk12
services:
  - docker

before_install:
  # install and run selenoid on virtual machine
  - curl -L -o cm https://github.com/aerokube/cm/releases/download/1.8.1/cm_linux_amd64
  - chmod +x ./cm
  - ./cm selenoid start --vnc
  - sudo usermod -aG docker $USER

script:
  - docker ps -a
  - docker images -a
  - mvn clean test #Runs tests and generates target/allure-results

after_script:
#  - mvn allure:serve #Build reports to temp folder and view:
#  - mvn allure:report #Build reports and save to target/site

#deploy:
#  provider: script
#  script: bash ./deploy.sh
#  on:
#    branch: master